jquick.banner.enabled=true
jquick.banner.version=3.3.0
jquick.banner.author=Martin
jquick.banner.github=@paohaijiao
jquick.banner.email=goudingcheng@gmail.com
jquick.banner.project=JQUICK
jquick.banner.slogan=https://github.com/paohaijiao