/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright (c) [2025-2099] Martin (goudingcheng@gmail.com)
 */
package com.github.paohaijiao.demo.footer;

import com.github.paohaijiao.executor.JQuickExcelCommonExportExecutor;
import com.github.paohaijiao.handler.JExcelExportHandler;
import com.github.paohaijiao.model.JExcelExportModel;
import com.github.paohaijiao.statement.JQuickRow;
import com.github.paohaijiao.xml.ex.JQuickExcelExportXmlParseFactory;
import com.github.paohaijiao.xml.factory.JQuickFactory;
import com.github.paohaijiao.xml.factory.JQuickXmlFactory;
import com.github.paohaijiao.xml.handler.JQuickParseHandler;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.Assert;
import org.junit.Test;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 分类：<b>FOOTER</b> —— 页脚文本。
 *
 * <p>固定文本页脚走 XML 规则（{@code demo/footer/jquick-excel.xml}），调用框架入口
 * {@link JQuickExcelExportXmlParseFactory}；动态页脚走编程式
 * {@link JExcelExportModel#setFooter(String)}（FOOTER 不做 ${...} 插值）。
 * 不封装任何公共方法，查找单元格的循环就地内联。产物目录：{@code D:\test\excel}。
 */
public class FooterDemo {

    private static final File OUT_DIR = new File("D:" + File.separator + "test" + File.separator + "excel");
    private static final String XML = "demo/footer/jquick-excel.xml";

    static {
        if (!OUT_DIR.exists()) {
            OUT_DIR.mkdirs();
        }
    }

    /** 固定文本页脚：FOOTER 写在 XML 规则中。 */
    @Test
    public void exportFooterFixed() throws Exception {
        List<JQuickRow> rows = new ArrayList<>();
        JQuickRow r1 = new JQuickRow();
        r1.put("a", "张三");
        r1.put("b", 20);
        rows.add(r1);
        JQuickRow r2 = new JQuickRow();
        r2.put("a", "李四");
        r2.put("b", 21);
        rows.add(r2);

        File out = new File(OUT_DIR, "footer-fixed.xlsx");
        try (OutputStream os = new FileOutputStream(out)) {
            JQuickParseHandler parser = new JQuickExcelExportXmlParseFactory(rows, os);
            JQuickFactory factory = new JQuickXmlFactory(parser, XML);
            FooterService service = factory.createApi(FooterService.class);
            service.exportFooterFixed("field", "value");
        }
        try (Workbook wb = new XSSFWorkbook(new FileInputStream(out))) {
            Sheet sheet = wb.getSheet("页脚");
            String text = null;
            for (Row row : sheet) {
                for (Cell cell : row) {
                    if (cell.getCellType() == CellType.STRING
                            && cell.getStringCellValue().contains("Generated by JQuickExcel")) {
                        text = cell.getStringCellValue();
                    }
                }
            }
            System.out.println("【FOOTER】固定页脚: " + text);
            Assert.assertEquals("Generated by JQuickExcel", text);
        }
    }

    /**
     * 动态页脚：FOOTER 不做 ${...} 插值，Java 侧把日期拼好后 setFooter，
     * 再用 JExcelExportHandler 写盘。
     */
    @Test
    public void exportFooterDynamic() throws Exception {
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

        List<JQuickRow> rows = new ArrayList<>();
        JQuickRow r1 = new JQuickRow();
        r1.put("a", "张三");
        r1.put("b", 20);
        rows.add(r1);
        JQuickRow r2 = new JQuickRow();
        r2.put("a", "李四");
        r2.put("b", 21);
        rows.add(r2);

        String dsl = "EXPORT WITH SHEET=\"页脚\", HEADER=true, MAPPING={\"a\":\"姓名\",\"b\":\"年龄\"}";
        JExcelExportModel model = (JExcelExportModel) new JQuickExcelCommonExportExecutor().execute(dsl);
        model.setFooter("Generated by JQuickExcel on " + date);
        JExcelExportHandler handler = new JExcelExportHandler(model, rows);

        File out = new File(OUT_DIR, "footer-dynamic.xlsx");
        try (OutputStream os = new FileOutputStream(out)) {
            handler.getWorkBook().write(os);
        }
        try (Workbook wb = new XSSFWorkbook(new FileInputStream(out))) {
            Sheet sheet = wb.getSheet("页脚");
            String text = null;
            for (Row row : sheet) {
                for (Cell cell : row) {
                    if (cell.getCellType() == CellType.STRING
                            && cell.getStringCellValue().contains("Generated by JQuickExcel on")) {
                        text = cell.getStringCellValue();
                    }
                }
            }
            System.out.println("【FOOTER】动态页脚: " + text);
            Assert.assertNotNull(text);
            Assert.assertTrue(text.endsWith(date));
        }
    }
}
