/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright (c) [2025-2099] Martin (goudingcheng@gmail.com)
 */
package com.github.paohaijiao.demo.footer;

import com.github.paohaijiao.demo.support.DemoKit;
import com.github.paohaijiao.executor.JQuickExcelCommonExportExecutor;
import com.github.paohaijiao.handler.JExcelExportHandler;
import com.github.paohaijiao.model.JExcelExportModel;
import com.github.paohaijiao.statement.JQuickRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.Assert;
import org.junit.Test;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * footer 子包 demo：固定页脚走 XML（{@code exportFooterFixed}），
 * 动态页脚走编程式（{@link JExcelExportModel#setFooter(String)}）。
 *
 * <p>独立规则文件：{@code demo/footer/jquick-excel.xml}。
 */
public class FooterDemo {

    /** 在整张 sheet 中查找包含指定文本的单元格。 */
    private static String findCellText(Sheet sheet, String keyword) {
        for (Row row : sheet) {
            for (Cell cell : row) {
                if (cell.getCellType() == CellType.STRING
                        && cell.getStringCellValue().contains(keyword)) {
                    return cell.getStringCellValue();
                }
            }
        }
        return null;
    }

    /** 固定文本页脚：FOOTER 写在 XML 规则中。 */
    @Test
    public void exportFooterFixed() throws Exception {
        List<JQuickRow> rows = DemoKit.toRows(DemoKit.personRows());
        File out = DemoKit.out("footer-fixed.xlsx");
        try (OutputStream os = new FileOutputStream(out)) {
            FooterService service = DemoKit.exportApi(
                    "demo/footer/jquick-excel.xml", rows, os, FooterService.class);
            service.exportFooterFixed("field", "value");
        }
        try (Workbook wb = new XSSFWorkbook(new FileInputStream(out))) {
            String text = findCellText(wb.getSheet("页脚"), "Generated by JQuickExcel");
            System.out.println("固定页脚: " + text);
            Assert.assertEquals("Generated by JQuickExcel", text);
        }
    }

    /**
     * 动态页脚：FOOTER 不做 ${...} 插值，Java 侧把日期拼好后 setFooter，
     * 再自己 new JExcelExportHandler 并 getWorkBook().write(os)。
     */
    @Test
    public void exportFooterDynamic() throws Exception {
        List<JQuickRow> rows = DemoKit.toRows(DemoKit.personRows());
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

        String dsl = "EXPORT WITH SHEET=\"页脚\", HEADER=true, MAPPING={\"a\":\"姓名\",\"b\":\"年龄\"}";
        JExcelExportModel model = (JExcelExportModel) new JQuickExcelCommonExportExecutor().execute(dsl);
        model.setFooter("Generated by JQuickExcel on " + date);
        JExcelExportHandler handler = new JExcelExportHandler(model, rows);

        File out = DemoKit.out("footer-dynamic.xlsx");
        try (OutputStream os = new FileOutputStream(out)) {
            handler.getWorkBook().write(os);
        }
        try (Workbook wb = new XSSFWorkbook(new FileInputStream(out))) {
            String text = findCellText(wb.getSheet("页脚"), "Generated by JQuickExcel on");
            System.out.println("动态页脚: " + text);
            Assert.assertNotNull(text);
            Assert.assertTrue(text.endsWith(date));
        }
    }
}
